version: "3.9"
services:
  redis:
    deploy:
      replicas: 1
    image: redis
    networks:
      default: null

  vote:
    image: ghcr.io/${REPOSITORY_OWNER:?}/vote:latest
    depends_on:
      redis:
        condition: service_started
    ports:
      - mode: ingress
        target: 80
        published: ${PORT:-8080}
        protocol: tcp
