apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

patchesStrategicMerge:
- deployment.yaml
- service.yaml

replicas:
  - name: vote
    count: 10

commonAnnotations:
  supported-by: support@fluxcd.io
commonLabels:
  project: instavote
  env: staging

configMapGenerator:
  - name: vote-options
    envs:
      - options.env

configMapGenerator:
  - name: vote-options
    envs:
      - options.env
