version: '2'

services:

  sut:
    image: ghcr.io/${REPOSITORY_OWNER-manquintero}/tests:latest
    build: ../tests/
    depends_on:
      - vote
      - result
      - worker
    networks:
      - front-tier
    environment:
      - OPENSSL_CONF=/dev/null

  vote:
    image: ghcr.io/${REPOSITORY_OWNER-manquintero}/vote:latest
    build:
      context: ../vote/
      dockerfile: Dockerfile-scratch
    ports: ["80"]
    depends_on:
      - redis
      - db
    networks:
      - front-tier
      - back-tier

  result:
    image: ghcr.io/${REPOSITORY_OWNER-manquintero}/result:latest
    build:
      context: ../result/
      args:
        - NODE_VERSION=13
    ports: ["80"]
    depends_on:
      - redis
      - db
    networks:
      - front-tier
      - back-tier

  worker:
    build: ../worker/
    image: ghcr.io/${REPOSITORY_OWNER-manquintero}/worker:latest
    depends_on:
      - redis
      - db
    networks:
      - back-tier

  redis:
    image: redis:alpine
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: postgres:9.4
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
