on:
  workflow_call:
    inputs:
      MICROSERVICE:
        description: "Component to build"
        type: string
        required: true
      VERSION:
        description: "Container build tag"
        type: string
        required: false
        default: "latest"
      DOCKERFILE:
        description: "Build plan file"
        type: string
        required: false
        default: Dockerfile
      BUILD-ARGS:
        description: "Build time arguments"
        type: string
        required: false

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          build-args: ${{ inputs.BUILD-ARGS }}
          context: "{{defaultContext}}:${{ inputs.MICROSERVICE }}"
          file: ${{ inputs.DOCKERFILE }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ inputs.MICROSERVICE }}:${{ inputs.VERSION }}